### ISSUE TITLE
percIns_predicted NaN

### ISSUE THREAD

**Issue by pabloyler** [julianeweller/MinsePIE#5]
Hello,

I installed MinsePIE and the required Python packages, but got 'NaN' for the `percIns_predicted` entry when I ran the example command given in the readme. I'm not well-versed in computer programming so I'm not sure what is going on--any help is greatly appreciated! Here is what I have...

What I got...
```
(pie) paulgo@dynamic-oit-vapornet100-10-9-53-229 MinsePIE % python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:47) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import minsepie
>>> x = minsepie.predict(['TGTCA'], pbs = 'CAGACTGAGCACG', ha = 'TGATGGCAGAGGAAAGGAAGCCCTGCTTCCTCCA', spacer = 'GGCCCAGACTGAGCACGTGA', mmr = 0, outdir = "./", model = "MinsePIE_v3.sav")
INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.
>>> x
  inputsequence                spacer                                  HA            PBS  mmr  mean   std insert  ... pos1compl  loop1_intact  VF_RTT  mean_RTT   std_RTT  VF_RTT_z    zscore  percIns_predicted
0         TGTCA  GGCCCAGACTGAGCACGTGA  TGATGGCAGAGGAAAGGAAGCCCTGCTTCCTCCA  CAGACTGAGCACG    0  None  None  TGTCA  ...     False          True   -13.2  -12.1114  1.531662 -0.710731  0.573928                NaN

[1 rows x 24 columns]
```

When I try using models MinsPIE.sav or MisePIE_v2.sav I get the following error...
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/pablo/proj/pe/MinsePIE/minsepie.py", line 54, in predict
    request = prediction(request, model_dict, model)
  File "/Volumes/pablo/proj/pe/MinsePIE/func_score.py", line 15, in prediction
    df['zscore']= pred_model.predict(df[features])
  File "/Users/paulgo/opt/anaconda3/envs/pie/lib/python3.8/site-packages/xgboost/core.py", line 1885, in predict
    raise TypeError('Expecting data to be a DMatrix object, got: ', type(data))
TypeError: ('Expecting data to be a DMatrix object, got: ', <class 'pandas.core.frame.DataFrame'>)
```
The current environment (not sure how to downgrade `viennarna` from 2.5.0a5):
```
(pie) paulgo@dynamic-oit-vapornet100-10-9-53-229 MinsePIE % conda list
# packages in environment at /Users/paulgo/opt/anaconda3/envs/pie:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    anaconda
argparse                  1.4.0                    pypi_0    pypi
biopython                 1.79                     pypi_0    pypi
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2022.5.18.1          h033912b_0    conda-forge
datetime                  4.4                      pypi_0    pypi
dill                      0.3.5.1                  pypi_0    pypi
joblib                    1.1.0              pyhd3eb1b0_0    anaconda
libblas                   3.9.0           15_osx64_openblas    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libcxx                    14.0.5               hce7ea42_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           11_2_0_h246ff09_26  
libgfortran5              11.2.0              h246ff09_26  
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libxgboost                1.5.1            cpu_h598c753_2    conda-forge
libzlib                   1.2.12               h6c3fc93_0    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
minsepie                  1.0                      pypi_0    pypi
more-itertools            8.12.0                   pypi_0    pypi
ncurses                   6.3                  h96cf925_1    conda-forge
numpy                     1.22.4           py38h3ad0702_0    conda-forge
openssl                   3.0.3                hfe4f2af_0    conda-forge
pandarallel               1.5.4                    pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
psutil                    5.9.0                    pypi_0    pypi
python                    3.8.13          h66c20e1_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1                   pypi_0    pypi
readline                  8.1.2                h3899abd_0    conda-forge
regex                     2021.8.3                 pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.3                    pypi_0    pypi
setuptools                62.3.4           py38h50d1736_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.5               hd9f0692_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
viennarna                 2.5.0a5                  pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xgboost                   1.5.0                    pypi_0    pypi
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.12               h6c3fc93_0    conda-forge
zope-interface            5.4.0                    pypi_0    pypi
```

Thank-you!

**Comment by pabloyler** [comment]
Ah -- I see what I did wrong -- sorry!

**Comment by pabloyler** [comment]
Ah! Misunderstood the `mean` and `std` fields -- sorry for the confusion!
